name: ingilizce_ogrenme_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_native_splash: ^2.4.7
  flutter_tts: ^4.2.5
  google_generative_ai: ^0.4.7
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/images/

# Logo konfigürasyonu
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/data/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F171E"
  adaptive_icon_foreground: "assets/data/images/logo.png"

flutter_native_splash:
  color: "#0F171E"
  image: assets/data/images/logo.png
  
  android_12:
    color: "#0F171E"
    image: assets/data/images/logo.png
    
  android: true
  ios: true
  fullscreen: true